загрузка конфига из файла + тесты
qa-dev/go-core pull request #1
Opened 2016-10-12 09:06 UTC by podtserkovsky

2016-10-12 17:36 UTC, makhov requested changes
Хранить файлы для тестов сразу в проекте – не самая лучшая идея. В тесте поковыряй в сторону `ioutil.TempFile` и записи в него из строки

2016-10-14 07:45 UTC, makhov requested changes

2016-10-14 07:45 UTC, makhov commented on config/config_test.go
> +	if err != nil {
Мы везде юзаем пакет `assert` из https://github.com/stretchr/testify, это гораздо удобнее

2016-10-14 07:45 UTC, makhov commented on config/config_test.go
> +		"{" +
можно просто вместо двойных кавычек использовать бэктики ( ` )

2016-10-17 10:11 UTC, andrskom commented on config/config_test.go
> +	tempFile := makeJsonFile("" +
Там вроде можно использовать ``` для того что бы многострочный текст писать.

2016-10-18 06:54 UTC, makhov commented
Миша, поправь мелочи, да замержим

2016-10-18 12:58 UTC, makhov approved these changes

2016-10-18 12:58 UTC, merged